"""
Template Integration Service
Merges AI-generated content with PwC template layouts
"""

import json
from typing import Dict, List, Optional
from pathlib import Path
from core.template_selector import PwCTemplateSelector
from core.logger_setup import app_logger as logger


class TemplateIntegrationService:
    """
    Service to integrate PwC templates with AI-generated presentation content
    """
    
    def __init__(self):
        self.selector = PwCTemplateSelector()
    
    def integrate_templates(self, ai_presentation: Dict) -> Dict:
        """
        Integrate templates into AI-generated presentation
        
        Args:
            ai_presentation: The JSON presentation generated by AI
        
        Returns:
            Enhanced presentation with template-based layouts
        """
        try:
            slides = ai_presentation.get("slides", [])
            total_slides = len(slides)
            
            logger.info(f"Integrating templates for {total_slides} slides")
            
            enhanced_slides = []
            
            for idx, slide in enumerate(slides):
                enhanced_slide = self._enhance_slide(slide, idx, total_slides)
                enhanced_slides.append(enhanced_slide)
            
            # Update presentation with enhanced slides
            ai_presentation["slides"] = enhanced_slides
            
            logger.info("Template integration complete")
            return ai_presentation
            
        except Exception as e:
            logger.error(f"Error integrating templates: {e}")
            # Return original presentation if integration fails
            return ai_presentation
    
    def _enhance_slide(self, slide: Dict, position: int, total_slides: int) -> Dict:
        """
        Enhance a single slide with template information
        
        Args:
            slide: Original slide dict
            position: Slide position (0-based)
            total_slides: Total number of slides
        
        Returns:
            Enhanced slide with template suggestions
        """
        try:
            # Get slide metadata if exists
            slide_metadata = slide.get("slide_metadata", {})
            suggested_template = slide_metadata.get("suggested_template")
            template_keywords = slide_metadata.get("template_keywords", [])
            
            # Build content description from slide
            title = slide.get("title", "")
            components = slide.get("components", [])
            
            # Extract text for content analysis
            content_text = title + " "
            for comp in components:
                if comp.get("type") == "text":
                    content_text += comp.get("value", "") + " "
                elif comp.get("type") == "richtext":
                    for run in comp.get("runs", []):
                        content_text += run.get("text", "") + " "
            
            # Select template if not already suggested
            if not suggested_template:
                template_result = self.selector.select_content_template(
                    slide_position=position,
                    content_description=content_text[:500],  # Limit to first 500 chars
                    content_keywords=template_keywords,
                    total_slides=total_slides
                )
                
                suggested_template = template_result.get("layout_type")
                
                # Log template selection for debugging (don't add to slide to avoid schema validation errors)
                logger.info(f"Slide {position}: Selected template '{suggested_template}' - {template_result.get('file', 'N/A')}")
            
            # Remove slide_metadata if it exists (not allowed by schema)
            if "slide_metadata" in slide:
                logger.debug(f"Removing slide_metadata from slide {position} (not allowed by schema)")
                del slide["slide_metadata"]
            
            return slide
            
        except Exception as e:
            logger.error(f"Error enhancing slide {position}: {e}")
            return slide
    
    def get_template_reference(self, layout_type: str) -> Optional[Dict]:
        """
        Get a reference template for a specific layout type
        
        Args:
            layout_type: Type of layout (e.g., "title_slides")
        
        Returns:
            Template information or None
        """
        return self.selector._get_template_from(layout_type)
    
    def apply_cover_template(self, title: str, subtitle: str = "", author: str = "") -> Dict:
        """
        Generate a cover slide using PwC cover templates
        
        Args:
            title: Presentation title
            subtitle: Optional subtitle
            author: Optional author name
        
        Returns:
            Cover slide dict with template
        """
        try:
            cover_template = self.selector.select_cover_template(title=title)
            
            if not cover_template:
                logger.warning("No cover template found, using default")
                return self._create_default_cover(title, subtitle, author)
            
            # Get the template structure
            template_data = cover_template.get("template", {})
            slide_data = template_data.get("slide", {})
            
            # Replace placeholder text with actual content
            components = slide_data.get("components", [])
            enhanced_components = []
            
            for comp in components:
                if comp.get("type") in ["text", "richtext"]:
                    # Update text components with actual content
                    if "value" in comp:
                        if "title" in comp.get("value", "").lower():
                            comp["value"] = title
                        elif "subtitle" in comp.get("value", "").lower():
                            comp["value"] = subtitle
                        elif "author" in comp.get("value", "").lower() or "name" in comp.get("value", "").lower():
                            comp["value"] = author
                    
                    if "runs" in comp:
                        for run in comp["runs"]:
                            if "title" in run.get("text", "").lower():
                                run["text"] = title
                            elif "subtitle" in run.get("text", "").lower():
                                run["text"] = subtitle
                            elif "name" in run.get("text", "").lower():
                                run["text"] = author
                
                enhanced_components.append(comp)
            
            # Build the cover slide (without slide_metadata - not allowed by schema)
            cover_slide = {
                "title": title,
                "background": slide_data.get("background", {"type": "solid", "color": "#FFFFFF"}),
                "components": enhanced_components
            }
            
            # Log cover selection for debugging
            logger.info(f"Applied cover template: ID={cover_template.get('id')}, Image={cover_template.get('image')}")
            
            return cover_slide
            
        except Exception as e:
            logger.error(f"Error applying cover template: {e}")
            return self._create_default_cover(title, subtitle, author)
    
    def _create_default_cover(self, title: str, subtitle: str = "", author: str = "") -> Dict:
        """Create a simple default cover slide"""
        return {
            "title": title,
            "background": {"type": "solid", "color": "#FFFFFF"},
            "components": [
                {
                    "type": "text",
                    "text_type": "title",
                    "value": title,
                    "style": {
                        "font_family": "Georgia",
                        "font_size": 44,
                        "bold": True,
                        "color": "#FFFFFF",
                        "fill": "#E0301E",
                        "align": "left"
                    },
                    "grid": {"col": 1, "span": 12, "row_h": 2, "y": 3}
                },
                {
                    "type": "text",
                    "text_type": "h2",
                    "value": subtitle,
                    "style": {
                        "font_family": "Arial",
                        "font_size": 28,
                        "bold": False,
                        "color": "#000000",
                        "align": "left"
                    },
                    "grid": {"col": 1, "span": 12, "row_h": 1, "y": 5.5}
                } if subtitle else None
            ]
        }


# Convenience function
def integrate_templates_into_presentation(presentation: Dict) -> Dict:
    """
    Quick function to integrate templates into a presentation
    
    Args:
        presentation: AI-generated presentation JSON
    
    Returns:
        Enhanced presentation with templates
    """
    service = TemplateIntegrationService()
    return service.integrate_templates(presentation)

